{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.api",
    "module": "gax",
    "version": "2.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.api",
          "module": "api-common",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-common-protos",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-credentials",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "gax-2.19.2.jar",
          "url": "gax-2.19.2.jar",
          "size": 371719,
          "sha512": "c2a3403fc0c8527bf53740b6caffb7e53ae1cbe7a5a1a7d9bbfe755e329154ab56533c4709e65db2a21547ca545319596dc1fba01d7f99b2e03a43e242fa58a6",
          "sha256": "d9610e8c727cd06f7c2341a6e652d7ab44a4ee43a09be31cf53a0b2e40fcef18",
          "sha1": "5e5fe9f2d8ff1c4aa2a943f5cee66edeb811ff6a",
          "md5": "ef934448da3f3430844b2db936db3d06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "io.opencensus",
          "module": "opencensus-api",
          "version": {
            "requires": "0.28.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.api",
          "module": "api-common",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-common-protos",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-credentials",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gax-2.19.2.jar",
          "url": "gax-2.19.2.jar",
          "size": 371719,
          "sha512": "c2a3403fc0c8527bf53740b6caffb7e53ae1cbe7a5a1a7d9bbfe755e329154ab56533c4709e65db2a21547ca545319596dc1fba01d7f99b2e03a43e242fa58a6",
          "sha256": "d9610e8c727cd06f7c2341a6e652d7ab44a4ee43a09be31cf53a0b2e40fcef18",
          "sha1": "5e5fe9f2d8ff1c4aa2a943f5cee66edeb811ff6a",
          "md5": "ef934448da3f3430844b2db936db3d06"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gax-2.19.2-guavashaded.jar",
          "url": "gax-2.19.2-guavashaded.jar",
          "size": 3734377,
          "sha512": "6728ce8f86ad39a8ff3673c2cd6965b688f679c7365bc03567b008ebdcf4487677fdfda73f3331cd15eb52563cd48021028314e677cba12f0a7ce48c5896ffd3",
          "sha256": "79cbc26631ab8a16f689167adb70b7ce2d0d7f6dae514cd8f48eb0be1da70ecf",
          "sha1": "aeae227c3f442cdb0663c7e9fe1604abf1af3531",
          "md5": "894e376bad0ce8cdade644397ff6e012"
        }
      ]
    }
  ]
}
