{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-annotations",
    "version": "2.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.12.2.jar",
          "url": "jackson-annotations-2.12.2.jar",
          "size": 75701,
          "sha512": "5011e9946045bfe23e2e8f06c50d0b325216fea735a3e83ff8de44650e03b03633463196e4cacd101a7ca4ecf1c1074c4d4ef6c5d21c3b4196cb395ac60993ab",
          "sha256": "558561786c071af202e849b6ae3d39c87ed417ecc83d45e398c12eb3bffa557b",
          "sha1": "a770cc4c0a1fb0bfd8a150a6a0004e42bc99fca",
          "md5": "332535aef84b64b67a549a9d0d40d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.12.2.jar",
          "url": "jackson-annotations-2.12.2.jar",
          "size": 75701,
          "sha512": "5011e9946045bfe23e2e8f06c50d0b325216fea735a3e83ff8de44650e03b03633463196e4cacd101a7ca4ecf1c1074c4d4ef6c5d21c3b4196cb395ac60993ab",
          "sha256": "558561786c071af202e849b6ae3d39c87ed417ecc83d45e398c12eb3bffa557b",
          "sha1": "a770cc4c0a1fb0bfd8a150a6a0004e42bc99fca",
          "md5": "332535aef84b64b67a549a9d0d40d"
        }
      ]
    }
  ]
}
