{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "mtjml3kqu5ayxnq3kjstrqfty4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.6.0.jar",
          "url": "okhttp-4.6.0.jar",
          "size": 788355,
          "sha512": "aee78e34bc49c059b8a9d7a3d9dc0330a46e9bcec35603699976576bc9bd409210a253cac0faac2197f6a2dafbb4243b012cf3090aa5dce754b819c4f93429dc",
          "sha256": "0480d35187423f2fca923c91511a279eb01f27f703afcef40780ae8af460a857",
          "sha1": "1885ec944e0a74e78359756e88ce656fd5a596d5",
          "md5": "cea62a51cc75e4793e609f756f88af61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.6.0.jar",
          "url": "okhttp-4.6.0.jar",
          "size": 788355,
          "sha512": "aee78e34bc49c059b8a9d7a3d9dc0330a46e9bcec35603699976576bc9bd409210a253cac0faac2197f6a2dafbb4243b012cf3090aa5dce754b819c4f93429dc",
          "sha256": "0480d35187423f2fca923c91511a279eb01f27f703afcef40780ae8af460a857",
          "sha1": "1885ec944e0a74e78359756e88ce656fd5a596d5",
          "md5": "cea62a51cc75e4793e609f756f88af61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.6.0-javadoc.jar",
          "url": "okhttp-4.6.0-javadoc.jar",
          "size": 261,
          "sha512": "49c3df00f1714236cf559bc2886a820ade40546dbaa90ab8c9c383e92cc92b415672403e0d8172ad90ea5d488ea0d1d3e8c40d79038fc599dae053d0fa787e1a",
          "sha256": "326f394fb2af455a505c5232a2677a6099633b03bfa5002d91c908c3d90e601f",
          "sha1": "64a8ec366b1951ba1e813e6acab103b96223aa4a",
          "md5": "46c0f742893c5e91396663db003076f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.6.0-sources.jar",
          "url": "okhttp-4.6.0-sources.jar",
          "size": 360143,
          "sha512": "7170e05b4471c6977b441a9444fe601d9ca343b28ab306464ae7cf1e6410486133f4612898dbc49e2e64fbcb34e2892d2c77b6e9d1acff8eb1239aab10eb58fa",
          "sha256": "0dbcdab468b9c70b0022920260f9357b058bba9d49a3041ef568ee56406c5249",
          "sha1": "46b747b470c8bb885006706f33b6eeab9a5a52a5",
          "md5": "710360df1994625052ab2cec58f82ec3"
        }
      ]
    }
  ]
}
