{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-cbor",
    "version": "2.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.14.2.jar",
          "url": "jackson-dataformat-cbor-2.14.2.jar",
          "size": 63050,
          "sha512": "7b59ae06d98649b450e1a3394bae3ad01aebdb84aa4954990e1257a838f3d3808b5d461507157b136b30ad5fa73681c3091fc89384cc575724b5c9e3849e1839",
          "sha256": "6ad93b9f9222487af86f7179621280e145a150276e4a7bb8fb6380cd28fbe7f1",
          "sha1": "90952676d8dc366e300085ad2d4443eb6f582269",
          "md5": "216f69550d71bfda04c4742e6ded26de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-cbor-2.14.2.jar",
          "url": "jackson-dataformat-cbor-2.14.2.jar",
          "size": 63050,
          "sha512": "7b59ae06d98649b450e1a3394bae3ad01aebdb84aa4954990e1257a838f3d3808b5d461507157b136b30ad5fa73681c3091fc89384cc575724b5c9e3849e1839",
          "sha256": "6ad93b9f9222487af86f7179621280e145a150276e4a7bb8fb6380cd28fbe7f1",
          "sha1": "90952676d8dc366e300085ad2d4443eb6f582269",
          "md5": "216f69550d71bfda04c4742e6ded26de"
        }
      ]
    }
  ]
}
