{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.jaxrs",
    "module": "jackson-jaxrs-json-provider",
    "version": "2.12.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-base",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-jaxrs-json-provider-2.12.7.jar",
          "url": "jackson-jaxrs-json-provider-2.12.7.jar",
          "size": 15400,
          "sha512": "e082c6f10d112aaa1031d1297d23cec033907f52aa0a4ff5bf6e3cfe1aaffe30a717c48390f779c4793b91d103eada77208fce8aa3d93383fd1b02058b107b47",
          "sha256": "8d870adf5dcd4793084d875e3f1dee4252907bc17d2fd435a7ed3f213e355709",
          "sha1": "b7cb299d9f002c2fedd2c184813cc9e3056752f6",
          "md5": "3b012357287aba83225a3e7429404e47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-base",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-jaxrs-json-provider-2.12.7.jar",
          "url": "jackson-jaxrs-json-provider-2.12.7.jar",
          "size": 15400,
          "sha512": "e082c6f10d112aaa1031d1297d23cec033907f52aa0a4ff5bf6e3cfe1aaffe30a717c48390f779c4793b91d103eada77208fce8aa3d93383fd1b02058b107b47",
          "sha256": "8d870adf5dcd4793084d875e3f1dee4252907bc17d2fd435a7ed3f213e355709",
          "sha1": "b7cb299d9f002c2fedd2c184813cc9e3056752f6",
          "md5": "3b012357287aba83225a3e7429404e47"
        }
      ]
    }
  ]
}
